[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/web",
    "packages/api",
    "packages/tokio_signal_handler"
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
ui = { path = "packages/ui" }
api = { path = "packages/api" }


[profile.android-dev]
inherits = "dev"

[profile.dev]
opt-level = 0
debug = 2

[profile.release]
opt-level = 3

[profile.server-dev]
inherits = "dev"

[profile.wasm-dev]
opt-level = 1
inherits = "dev"
