services:
  web:
    build:
      context: .
      dockerfile: webapp/Dockerfile
      target: base
    env_file: .env
    ports:
      - "${FRONT_PORT}:8080"
      - "${API_PORT}:8000"
    volumes:
      - "./webapp:/usr/src/myapp"

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    user: ":"
    command: >
      start --log info
      --user $SURREALDB_USER
      --pass $SURREALDB_PASS
      rocksdb://data
    env_file:
      - .env
    ports:
      - "${BDD_PORT}:8000"
    volumes:
      - ./bdd:/data
