services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    user: ":"
    command: >
      start --log info
      --user $SURREALDB_USER
      --pass $SURREALDB_PASS
      rocksdb://data
    env_file:
      - .env
    ports:
      - "${BDD_PORT}:8000"
    volumes:
      - ./bdd:/data

  tokio_middleware:
    build:
      context: ./tokio_signal_handler
      dockerfile: Dockerfile
      target: runtime
    env_file: .env
    ports:
      - "${TOKIO_PORT}:9000"
      - "${TOKIO_CONSOLE_PORT}:6669"
