services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    user: ":"
    command: >
      start --log info
      --user $SURREALDB_USER
      --pass $SURREALDB_PASS
      rocksdb://data
    env_file:
      - .env
    ports:
      - "${BDD_PORT}:8000"
    volumes:
      - ./bdd:/data

  tokio_middleware:
    build:
      context: ./tokio_signal_handler
      dockerfile: Dockerfile
      target: runtime
    env_file: .env
    ports:
      - "${TOKIO_PORT}:9000"
      - "${TOKIO_CONSOLE_PORT}:6669"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${BACKEND_PORT}:5432"
    depends_on:
      - surrealdb
      - tokio_middleware

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
