[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
faker_rand = "0.1.1"
rand = "0.9.1"
serde = { version = "1.0.209", features = ["derive"] }
surrealdb = "2.3.3"
thiserror = "2.0.12"
tokio = "1.45.1"